name: Maintain code quality

on:
  push:
  pull_request:
  pull_request_review:

permissions:
  contents: read

jobs:
  test:
    name: Test
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: pnpm/action-setup@11dd14d0c0916e1ad9ff1938d8d4ea509bebfe10
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Test
        run: pnpm test
