name: Maintain code quality

on:
  push:
  pull_request:
  pull_request_review:

permissions:
  contents: read

jobs:
  test:
    name: Test
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: pnpm/action-setup@d2613e087f2e0aa841925861c5a5f7395d552177
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Test
        run: pnpm test
