name: Maintain code quality

on:
  push:
  pull_request:
  pull_request_review:

permissions:
  contents: read

jobs:
  test:
    name: Test
    if: github.event_name == 'push' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Test
        run: pnpm test
